### ISSUE TITLE
Linux weekly digest

### ISSUE THREAD

**Issue by rsarky** [lfd/PaStA#47]
A weekly (could be for any appropriate timescale)  digest that presents a number of statistics about the Linux kernel development process in a concise and informative way. Eg. Patches accepted/rejected/ignored by subsystem. top patch submitters, top reviewers, number of lines of code added/deleted etc.

**Comment by rralf** [comment]
You should look at the bitergia / patchwork stuff. There might already be some preexisting work.

**Comment by rsarky** [comment]
Oh. I kind of expected this though, will check it out

**Comment by bulwahn** [comment]
We are already considering this for a while. The appropriate time scale is probably every full release cycle, because the differences per week are mainly dependent where we are in the release cycle. Further, patches accepted/rejected/ignored can only be determined after a few weeks/months when they show up in the git repositories.

Now to the specific stats:

- ignored patches: is actually quite stable, and quite independent of subsystem; more dependent on the contributor.
- top patch submitters: doable, very similar to top git authors, though.
- top reviewers: Anmol is actually looking into exactly that at the moment.
- LoC added/deleted: Jonathan Corbet already collects and presents that information.

**Comment by bulwahn** [comment]
I consider off-list patches interesting (because they are changing over time and interesting for other reasons). Also, top reviewers is interesting, but the really interesting aspect is to present author-reviewer-file relationships in a comprehensible manner (that is pretty stable over time, though.).

**Comment by rsarky** [comment]
> We are already considering this for a while. The appropriate time scale is probably every full release cycle, because the differences per week are mainly dependent where we are in the release cycle.

Makes sense. Anyway the timescale shouldn't reallly have an impact on the implementation.

> Further, patches accepted/rejected/ignored can only be determined after a few weeks/months when they show up in the git repositories.

Oh yes. That's something that I missed. Do you have any solution for this as you mentioned `ignored patches` in the list of stats.

Also we can report threads that have been most actively discussed by the community.
Applying some NLP methods for sentiment analysis may allow us to discover the most polarising threads.
The stability of various subsystem as a function of bug reports is also going to be an interesting metric.

**Comment by rsarky** [comment]
Any idea how [these](https://lwn.net/Articles/821813/) statistics are currently generated by lwn?

**Comment by rralf** [comment]
Have a look at git://git.lwn.net/gitdm.git 

@ditzlike is currently also trying to find out how it's exactly generating graphs.
