### ISSUE TITLE
Have an option to only run representative analyses (No repository required)

### ISSUE THREAD

**Issue by rsarky** [lfd/PaStA#79]
There have been situations when I setup PaStA and I only want to use it for representative analyses of a mailbox. In this case I dont need an upstream repository, I dont want to clone the entire linux kernel. What I end up doing is just setting up a dummy repository in place of the project repository as a work around now.

Would it be useful to provide an option to run representative analyses without requiring the user to have a upstream repository?

**Comment by rralf** [comment]
In what exact situations don't you need the repository? Could you tell me a user story?

**Comment by rsarky** [comment]
This might be too specific, 
But say in the case of patchwork interaction where we don't need upstream references at this point bit only representative analyses

**Comment by rralf** [comment]
but even for patchwork, we will need to run 'pasta analyse upstream', so we will need the repository.

**Comment by rsarky** [comment]
At this point we don't need to run that right?
Since we are not using the upstream mappings

**Comment by rralf** [comment]
What would the result be useful for?

**Comment by rsarky** [comment]
We only need pasta analyse rep for the patch groups file that we currently ingest in patchwork using replacerelations command

**Comment by rralf** [comment]
Ah, now I see (currently reviewing your integration script). We currently don't push upstream commit hashes to patchwork. You need to refresh my memories: What was the reason that we don't do that?

**Comment by rsarky** [comment]
Patchwork has its own way of figuring out upstream mappings, I don't exactly know how that works. Also it has no way of relating a patch to multiple upstream commits.
In our model downstream patches can be linked to multiple upstream commits

**Comment by rralf** [comment]
To overcome this issue, we could, for example, map clusters with more that one commit only to the oldest commit hash. In the linux/2017 analysis, for example, 98% of all clusters contain exactly one commit. So for the vast majority that wouldn't be an issue.

Anyway, that's beyond the scope of your project. If you want to introduce that we don't need a repository, I would expect that PaStA supports that case by design, and not by introducing an empty dummy repo (because this might lead to confusion). I can't say how complex that would be, recommendations welcome.
